(function () {
  var API_BASE = window.SMART_TRAVEL_API_URL || 'http://localhost:8000';
  var selectedTours = [];
  var routeData = null;
  var money = new Intl.NumberFormat('vi-VN');
  var today = new Date().toISOString().slice(0, 10);
  var dateInput = document.getElementById('routeDate');
  if (dateInput) { dateInput.min = today; dateInput.value = today; }

  function escapeHtml(value) { return String(value == null ? '' : value).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;').replace(/'/g, '&#039;'); }
  function formatMoney(value) { return money.format(Number(value) || 0) + '₫'; }
  function setStatus(message, error) { var status = document.getElementById('plannerStatus'); status.textContent = message || ''; status.className = 'planner-status' + (error ? ' is-error' : ''); }

  function renderRoute(data) {
    routeData = data;
    selectedTours = [];
    document.getElementById('plannerResult').hidden = false;
    document.getElementById('routeSummary').innerHTML = '<div><span>Tuyến đề xuất</span><strong>' + escapeHtml(data.origin) + ' → ' + escapeHtml(data.destination) + '</strong></div><div><strong>' + escapeHtml(data.distance_km) + ' km</strong><span>Khoảng ' + escapeHtml(data.duration_minutes) + ' phút di chuyển</span></div>';
    var points = data.points || [];
    var coordinates = points.map(function (point) { return point.longitude + ',' + point.latitude; }).join(';');
    document.getElementById('routeMap').innerHTML = '<iframe title="Bản đồ tuyến đường" loading="lazy" src="https://www.openstreetmap.org/export/embed.html?bbox=105.75%2C20.15%2C106.05%2C21.12&layer=mapnik&marker=' + points[points.length - 1].latitude + '%2C' + points[points.length - 1].longitude + '"></iframe>';
    document.getElementById('routeStops').innerHTML = points.map(function (point) { return '<div class="route-stop"><span class="route-stop-number">' + point.order + '</span><div><strong>' + escapeHtml(point.name) + '</strong><small>' + (point.role === 'origin' ? 'Điểm xuất phát' : point.role === 'destination' ? 'Điểm đến' : 'Điểm dừng trên đường') + '</small></div><time>' + (point.estimated_minutes_from_previous ? point.estimated_minutes_from_previous + ' phút' : 'Bắt đầu') + '</time></div>'; }).join('');
    document.getElementById('routeTours').innerHTML = (data.tours || []).map(function (tour) { return '<article class="planner-tour" data-tour-id="' + escapeHtml(tour.tour_id) + '"><img src="' + escapeHtml(tour.image_url || 'https://images.unsplash.com/photo-1528127269322-539801943592?auto=format&fit=crop&w=800&q=80') + '" alt="' + escapeHtml(tour.title) + '"><div class="planner-tour-body"><span class="eyebrow eyebrow-muted">' + escapeHtml(tour.route_point) + ' · ' + escapeHtml(tour.distance_to_route_km) + ' km lệch tuyến</span><h3>' + escapeHtml(tour.title) + '</h3><div class="planner-tour-meta"><span><i class="bx bxs-star"></i> ' + escapeHtml(tour.rating) + '</span><span>' + escapeHtml(tour.location) + '</span></div><div class="planner-tour-foot"><strong>' + formatMoney(tour.price) + '</strong><button type="button" class="btn btn-outline btn-small planner-add-tour">Thêm vào combo</button></div></div></article>'; }).join('') || '<p class="text-muted">Chưa có tour phù hợp gần tuyến này.</p>';
    document.querySelectorAll('.planner-add-tour').forEach(function (button) { button.addEventListener('click', function () { toggleTour(button.closest('.planner-tour').getAttribute('data-tour-id')); }); });
    renderCombo();
  }

  function toggleTour(id) { var tour = routeData.tours.find(function (item) { return item.tour_id === id; }); var index = selectedTours.findIndex(function (item) { return item.tour_id === id; }); if (index >= 0) selectedTours.splice(index, 1); else selectedTours.push(tour); document.querySelector('[data-tour-id="' + id + '"]').classList.toggle('selected', index < 0); renderCombo(); }
  function renderCombo() { document.getElementById('selectedCount').textContent = selectedTours.length + ' tour'; document.getElementById('comboItems').innerHTML = selectedTours.length ? selectedTours.map(function (tour) { return '<div class="combo-item"><div><strong>' + escapeHtml(tour.title) + '</strong><small>' + escapeHtml(tour.route_point) + '</small></div><strong>' + formatMoney(tour.price) + '</strong></div>'; }).join('') : '<p class="text-muted">Chọn tour gần tuyến để thêm vào combo.</p>'; var adults = Number(document.getElementById('routeAdults').value) || 1; var children = Number(document.getElementById('routeChildren').value) || 0; var total = selectedTours.reduce(function (sum, tour) { return sum + tour.price * adults + tour.price * .5 * children; }, 0); document.getElementById('comboTotal').textContent = formatMoney(total); }

  document.getElementById('routePlanForm').addEventListener('submit', async function (event) { event.preventDefault(); setStatus('Đang tính tuyến và tìm tour gần hành trình...'); try { var response = await fetch(API_BASE + '/api/routes/plan', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ origin: document.getElementById('routeOrigin').value, destination: document.getElementById('routeDestination').value, travel_date: dateInput.value, adults: Number(document.getElementById('routeAdults').value), children: Number(document.getElementById('routeChildren').value) }) }); var data = await response.json(); if (!response.ok) throw new Error(data.detail || 'Không thể lập tuyến.'); renderRoute(data); setStatus(data.message); } catch (error) { setStatus(error.message, true); } });
  document.getElementById('routeAdults').addEventListener('change', renderCombo); document.getElementById('routeChildren').addEventListener('change', renderCombo);
  document.getElementById('createComboBtn').addEventListener('click', async function () { if (!selectedTours.length) { setStatus('Hãy chọn ít nhất một tour cho combo.', true); return; } var token = localStorage.getItem('access_token'); if (!token) { setStatus('Bạn cần đăng nhập trước khi đặt combo.', true); window.location.href = 'auth.html?redirect=trip-planner.html'; return; } var button = this; button.disabled = true; try { var response = await fetch(API_BASE + '/api/bookings/combo', { method: 'POST', headers: { 'Content-Type': 'application/json', Authorization: 'Bearer ' + token }, body: JSON.stringify({ items: selectedTours.map(function (tour) { return { tour_id: tour.tour_id, travel_date: dateInput.value }; }), adults: Number(document.getElementById('routeAdults').value), children: Number(document.getElementById('routeChildren').value), payment_method: document.getElementById('comboPayment').value, contact_phone: document.getElementById('comboPhone').value }) }); var data = await response.json(); if (!response.ok) throw new Error(data.detail || 'Không thể tạo combo.'); if (data.payment_method === 'qr') { var confirmResponse = await fetch(API_BASE + '/api/payments/qr/confirm', { method: 'POST', headers: { 'Content-Type': 'application/json', Authorization: 'Bearer ' + token }, body: JSON.stringify({ booking_id: data.id }) }); if (!confirmResponse.ok) throw new Error('Không thể xác nhận thanh toán QR.'); window.location.href = 'profile.html?combo=' + encodeURIComponent(data.id); return; } var paymentResponse = await fetch(API_BASE + '/api/payments/vnpay/create-combo', { method: 'POST', headers: { 'Content-Type': 'application/json', Authorization: 'Bearer ' + token }, body: JSON.stringify({ booking_id: data.id }) }); var payment = await paymentResponse.json(); if (!paymentResponse.ok) throw new Error(payment.detail || 'Không thể tạo thanh toán.'); window.location.href = payment.payment_url; } catch (error) { setStatus(error.message, true); button.disabled = false; } });
}());
